### ISSUE TITLE
ability to add private registries

### ISSUE THREAD

**Issue by kajanth** [rancher/helm-controller#17]
Currently helm-controller supports default registry and anything passed through spec.

Is it possible to add support for private helm registries.

e.g. we currently use AWS s3 for the registry with IAM role
this requires s3 plugin for helm `https://github.com/hypnoglow/helm-s3.git`
 
could this be done in a modular way so we can potentially pass in the klipper image as a value. https://github.com/rancher/helm-controller/blob/d5f5c830231110722f14d446d3b2038e5cdf1532/pkg/helm/controller.go#L40

**Comment by sacreman** [comment]
Private Helm registry works with with basic auth in the repo url. As a workaround we installed Chart Museum as a front end to the S3 bucket and use a CRD similar to below.

```
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: example 
  namespace: helm-controller
spec:
  chart: example
  version: 1.0.0
  repo: https://user:password@charts.example.com
  targetNamespace: default
```

I think this issue can be closed.
