### ISSUE TITLE
Edit CRD Causes Errors

### ISSUE THREAD

**Issue by luthermonson** [rancher/helm-controller#21]
If you add a CRD like the following

```
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: traefik-test
  namespace: kube-system
spec:
  chart: stable/traefik
  version: 1.64.0
  set:
    rbac.enabled: "true"
    ssl.enabled: "true"
```
let the helm jobs finish and you will have a new traefik pod. now edit the CR and change the version to `1.65.0`. The onchange comes through and it tries to spin up a job but since the job already exists from the previous run it will try to rewrite the existing one and some job fields are immutable and you will get something like the following:
```
E0716 12:58:30.843044       1 controller.go:118] error syncing 'helm-controller/grafana': handler helm-controller: failed to update helm-controller/helm-install-grafana batch/v1, Kind=Job for helm-controller helm-controller/grafana: Job.batch "helm-install-grafana" is invalid: spec.template: Invalid value: <<<large blob of job data>>>  field is immutable, requeuing```

need to handle edits a bit nicer and figure out how to do official upgrades to charts.
