### ISSUE TITLE
Helm-Controller dosen't support booleans correctly

### ISSUE THREAD

**Issue by Tedyst** [rancher/helm-controller#25]
With this manifest, Helm-Controller parses the key acme.staging as a string "false", not as a boolean. Because of this, Helm-Controller will use the argument `--set-string` instead of the argument `--set`, which will treat `false` as a boolean.
```yaml
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: traefik
  namespace: kube-system
spec:
  chart: https://%{KUBERNETES_API}%/static/charts/traefik-1.77.1.tgz
  set:
    acme.staging: "false"
```
