### ISSUE TITLE
Cannot delete charts

### ISSUE THREAD

**Issue by brandonkal** [rancher/helm-controller#33]
As the title says. I have several charts that just won't delete. kubectl hangs after saying a chart was deleted (but it is not).
No job is started to delete the chart.

**Comment by jdmarble** [comment]
I'm working around the problem by deleting the entire cluster and starting over. :laughing:

**Comment by brandonkal** [comment]
That's exactly what I had to do. Now I'm just templating out of cluster. I'm not sure why the finalizer doesn't run.

**Comment by zifeo** [comment]
In my case, I manage to overcome this by editing the `HelmChart` and setting `metadata.finalizers` to an empty list (rke2).

**Comment by rasmusson** [comment]
Anyone looking at this?

**Comment by cornfeedhobo** [comment]
@rasmusson no

**Comment by schlichtanders** [comment]
Here a HelmChart example which does not get cleaned up properly:
```yaml
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: csi-s3
  namespace: kube-system
spec:
  repo: https://yandex-cloud.github.io/k8s-csi-s3/charts
  chart: csi-s3
  version: 0.41.1
  targetNamespace: kube-system
  valuesContent: |-
    # we create the secret using kustomize
    secret:
      create: false
```
