### ISSUE TITLE
Condition on subchart not respected

### ISSUE THREAD

**Issue by gbonnefille** [rancher/helm-controller#38]
I'm trying to deploy [Sonarqube chart](https://github.com/Oteemo/charts/tree/master/charts/sonarqube) with the (partial) HelmChart:

```YAML
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: sonarqube
  namespace: kube-system
spec:
  chart: sonarqube
  repo: https://oteemo.github.io/charts
  targetNamespace: default
  valuesContent: |-
    database.type: h2
    postgresql.enabled: false
    mysql.enabled: false
    plugins:
      install:
        - https://github.com/mc1arke/sonarqube-community-branch-plugin/releases/download/1.1.1/sonarqube-community-branch-plugin-1.1.1.jar
```

But the postgres subchart is deployed, while it has a condition in `requirements.yaml`:

```YAML
dependencies:
- name: postgresql
  version: 8.6.4
  repository: https://charts.bitnami.com/bitnami
  condition: postgresql.enabled
```

What I'm doing wrong?
